const RUSSIAN_LETTER_TABLE = new Map<string, number>();

RUSSIAN_LETTER_TABLE.set('а', 1);
RUSSIAN_LETTER_TABLE.set('б', 2);
RUSSIAN_LETTER_TABLE.set('в', 4);
RUSSIAN_LETTER_TABLE.set('г', 7);
RUSSIAN_LETTER_TABLE.set('д', 4);
RUSSIAN_LETTER_TABLE.set('е', 5);
RUSSIAN_LETTER_TABLE.set('ё', 5); // если ё в начале имени то тогда значение 6
RUSSIAN_LETTER_TABLE.set('ж', 16);
RUSSIAN_LETTER_TABLE.set('з', 8);
RUSSIAN_LETTER_TABLE.set('и', 9);
RUSSIAN_LETTER_TABLE.set('й', 7); //adjust
RUSSIAN_LETTER_TABLE.set('к', 2);
RUSSIAN_LETTER_TABLE.set('л', 3);
RUSSIAN_LETTER_TABLE.set('м', 4);
RUSSIAN_LETTER_TABLE.set('н', 5);
RUSSIAN_LETTER_TABLE.set('о', 6);
RUSSIAN_LETTER_TABLE.set('п', 7);
RUSSIAN_LETTER_TABLE.set('р', 2);
RUSSIAN_LETTER_TABLE.set('с', 1);
RUSSIAN_LETTER_TABLE.set('т', 2);
RUSSIAN_LETTER_TABLE.set('у', 3);
RUSSIAN_LETTER_TABLE.set('ф', 6);
RUSSIAN_LETTER_TABLE.set('х', 8);
RUSSIAN_LETTER_TABLE.set('ц', 3);
RUSSIAN_LETTER_TABLE.set('ч', 11);
RUSSIAN_LETTER_TABLE.set('ш', 9);
RUSSIAN_LETTER_TABLE.set('щ', 12);
RUSSIAN_LETTER_TABLE.set('ъ', 0);
RUSSIAN_LETTER_TABLE.set('ы', 7);
RUSSIAN_LETTER_TABLE.set('ь', 0);
RUSSIAN_LETTER_TABLE.set('э', 5);
RUSSIAN_LETTER_TABLE.set('ю', 3);
RUSSIAN_LETTER_TABLE.set('я', 1);

export default RUSSIAN_LETTER_TABLE